sudo: false
language: go
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2eeb5739b1e1_key -iv $encrypted_2eeb5739b1e1_iv
  -in travis.pem.enc -out travis.pem -d
- chmod 400 travis.pem
install:
- go get -v github.com/gohugoio/hugo
script:
- hugo version
- rm -rf public
- hugo
- rsync -avz -e "ssh -i travis.pem" --delete public/ root@139.224.129.61:/var/www/
- ssh -i travis.pem root@139.224.129.61 "chown -R www-data:www-data /var/www"
addons:
  ssh_known_hosts: 139.224.129.61
