sudo: false
language: python
python:
- "3.6"
branches:
  only:
  - master
addons:
  ssh_known_hosts: 139.224.129.61

before_install:
- openssl aes-256-cbc -K $encrypted_2eeb5739b1e1_key -iv $encrypted_2eeb5739b1e1_iv
  -in travis.pem.enc -out travis.pem -d && chmod 400 travis.pem
- mkdir -p content

install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.49/hugo_extended_0.49_Linux-64bit.deb && sudo dpkg -i hugo*.deb && hugo version
- pip install Pygments
- rm -rf public 2> /dev/null

script:
- hugo &&
  rsync -avz -e "ssh -i travis.pem" --delete public/ root@139.224.129.61:/var/www/ &&
  ssh -i travis.pem root@139.224.129.61 "chown -R www-data:www-data /var/www"