sudo: false
language: go
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_2eeb5739b1e1_key -iv $encrypted_2eeb5739b1e1_iv
  -in travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
install:
- go get -v github.com/gohugoio/hugo
script:
- hugo version
deploy:
  provider: script
  skip_cleanup: true
  script:
  - touch hehe.txt
  on:
    branch: master
addons:
  ssh_known_hosts: 139.224.129.61
