baseURL = "https://chenyanzhe.com"
languageCode = "en-us"
title = "诸思码记"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

[menu]
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 4

[params]
    since = 2017
    author = "陈彦哲"                                 # Author's name
    avatar = "/images/me/avatar.jpg"                 # Author's avatar
    subtitle = "不积跬步，无以至千里"                   # Subtitle
    cdn_url = ""                                     # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = "沪ICP备18037058号"                        # ICP主体备案号
    baiduAnalytics = ""

    license= '本作品采用<a rel="license" href="https://creativecommons.org/licenses/by/4.0/">知识共享署名 4.0 国际许可协议</a>进行许可。'

[params.social]
    GitHub = "chenyanzhe"
    Twitter = "yanzhe_chen"
    LinkedIn = "yanzhe-chen-9598a9a6"
    Wechat = "/images/me/wechat.jpeg"  # Wechat QRcode image
    Email   = "yanzhe.cn@gmail.com"

